CocktailMagician/CocktailMagician/Models/CocktailReviewViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CocktailMagician.Web.Models
{
    public class CocktailReviewViewModel
    {
        public CocktailReviewViewModel()
        {

        }
        [Required]
        //[Range(1, 5, ErrorMessage = "Rating is between 1-5")]
        public double Rating { get; set; }

        //[MaxLength(500, ErrorMessage = "Use maximum 500 chars for your comment")]
        public string Comment { get; set; }
        public int CocktailId { get; set; }
        public string CocktailName { get; set; }
        public int AuthorId { get; set; }
        public string Author { get; set; }
    }
}

CocktailMagician/CocktailMagician/Controllers/CocktailsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CocktailMagician.Services.Contracts;
using CocktailMagician.Web.Mappers.Contracts;
using Microsoft.AspNetCore.Mvc.Rendering;
using CocktailMagician.Web.Models;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using NToastNotify;
using CocktailMagician.Web.Utilities;
using Ganss.XSS;
using Microsoft.AspNetCore.Identity;
using CocktailMagician.Models;

namespace CocktailMagician.Web.Controllers
{
    public class CocktailsController : Controller
    {
        private readonly ICocktailService cocktailService;
        private readonly IIngredientService ingredientService;
        private readonly IBarService barService;
        private readonly ICocktailDTOMapper cocktailDTOMapper;
        private readonly IIngredientDTOMapper ingredientDTOMapper;
        private readonly IBarDTOMapper barDTOMApper;
        private readonly IToastNotification toaster;
        private readonly UserManager<User> userManager;

        public CocktailsController(
            ICocktailService cocktailService,
            IIngredientService ingredientService,
            IBarService barService,
            ICocktailDTOMapper cocktailDTOMapper,
            IIngredientDTOMapper ingredientDTOMapper,
            IBarDTOMapper barDTOMApper,
            IToastNotification toaster,
            UserManager<User> userManager
            )
        {
            this.cocktailService = cocktailService ?? throw new ArgumentNullException(nameof(cocktailService));
            this.ingredientService = ingredientService ?? throw new ArgumentNullException(nameof(ingredientService));
            this.barService = barService ?? throw new ArgumentNullException(nameof(barService));
            this.cocktailDTOMapper = cocktailDTOMapper ?? throw new ArgumentNullException(nameof(cocktailDTOMapper));
            this.ingredientDTOMapper = ingredientDTOMapper ?? throw new ArgumentNullException(nameof(ingredientDTOMapper));
            this.barDTOMApper = barDTOMApper ?? throw new ArgumentNullException(nameof(barDTOMApper));
            this.toaster = toaster ?? throw new ArgumentNullException(nameof(toaster));
            this.userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            try
            {
                var cocktailDTOs = await this.cocktailService.GetAllCocktailssAsync();
                var cocktailVMs = cocktailDTOs.Select(cocktailDTO =>
                    cocktailDTOMapper.MapToVMFromDTO(cocktailDTO)).ToList();

                foreach (var cocktail in cocktailVMs)
                {
                    cocktail.Ingredients = (await this.ingredientService.GetAllIngredientsAsync())
                        .Where(ingredient => ingredient.CocktailDTOs.Any(c => c.Name == cocktail.Name))
                        .Select(idto => ingredientDTOMapper.MapToVMFromDTO(idto)).ToList();
                    cocktail.Bars = (await this.barService.GetAllBarsAsync())
                        .Where(bar => bar.Cocktails.Any(c => c.Name == cocktail.Name))
                        .Select(bdto => barDTOMApper.MapToVMFromDTO(bdto)).ToList();
                }

                return View(cocktailVMs);
            }
            catch (Exception)
            {
                this.toaster.AddWarningToastMessage(ToastrConsts.GenericError);
                return RedirectToAction("Index", "Home", new { area = "" });
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var cocktailDTO = await this.cocktailService.GetCocktailAsync(id);

                if (cocktailDTO == null)
                {
                    this.toaster.AddWarningToastMessage(ToastrConsts.NotFound);
                    return RedirectToAction(nameof(Index));
                }

                var cocktailVM = this.cocktailDTOMapper.MapToVMFromDTO(cocktailDTO);

                return View(cocktailVM);
            }
            catch (Exception)
            {
                this.toaster.AddWarningToastMessage(ToastrConsts.GenericError);
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        [Authorize(Roles = "Cocktail Magician")]
        public async Task<IActionResult> Create()
        {
            try
            {
                var ingredients = await this.ingredientService.GetAllIngredientsAsync();
                var ingredientVMs = ingredients.Select(ingredient => ingredientDTOMapper.MapToVMFromDTO(ingredient));

                ViewData["Ingredients"] = new MultiSelectList(ingredientVMs, "Id", "Name");
                return View();
            }
            catch (Exception)
            {
                this.toaster.AddWarningToastMessage(ToastrConsts.GenericError);
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Cocktail Magician")]
        public async Task<IActionResult> Create(CreateCocktailViewModel createCocktailViewModel)
        {
            var sanitizer = new HtmlSanitizer();
            createCocktailViewModel.Name = sanitizer.Sanitize(createCocktailViewModel.Name);

            if (createCocktailViewModel.File == null)
            {
                this.toaster.AddWarningToastMessage(ToastrConsts.NoPicture);
                return RedirectToAction(nameof(Create));
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (createCocktailViewModel.File.Length > 0)
                    {
                        MemoryStream ms = new MemoryStream();
                        await createCocktailViewModel.File.CopyToAsync(ms);
                        createCocktailViewModel.ImageData = ms.ToArray();

                        ms.Close();
                        ms.Dispose();
                    }

                    var cocktailDTO = this.cocktailDTOMapper.MapToDTOFromVM(createCocktailViewModel);

                    var validationResult = this.cocktailService.ValidateCocktail(cocktailDTO);

                    if (!validationResult.HasProperInputData)
                    {
                        this.toaster.AddWarningToastMessage(ToastrConsts.NullModel);
                        return RedirectToAction(nameof(Create));
                    }
                    if (!validationResult.HasProperNameLength)
                    {
                        this.toaster.AddWarningToastMessage(ToastrConsts.WrongNameLength);
                        return RedirectToAction(nameof(Create));
                    }
                    if (!validationResult.HasValidName)
                    {
                        this.toaster.AddWarningToastMessage(ToastrConsts.NameNotValid);
                        return RedirectToAction(nameof(Create));
                    }

                    bool isUnique = this.cocktailService.CocktailIsUnique(cocktailDTO);

                    if (!isUnique)
                    {
                        this.toaster.AddWarningToastMessage(ToastrConsts.NotUnique);
                        return RedirectToAction(nameof(Create));
                    }

                    var currentUserId = int.Parse(userManager.GetUserId(HttpContext.User));
                    cocktailDTO.CreatorId = currentUserId;

                    await this.cocktailService.CreateCocktailAsync(cocktailDTO);

                    this.toaster.AddSuccessToastMessage(ToastrConsts.Success);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    this.toaster.AddWarningToastMessage(ToastrConsts.GenericError);
                    return RedirectToAction(nameof(Create));
                }
            }
            this.toaster.AddWarningToastMessage(ToastrConsts.IncorrectInput);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize(Roles = "Cocktail Magician")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var ingredients = await this.ingredientService.GetAllIngredientsAsync();
                var ingredientVMs = ingredients.Select(ingredient => ingredientDTOMapper.MapToVMFromDTO(ingredient));
                var bars = await this.barService.GetAllBarsAsync();
                var barVMs = bars.Select(bar => barDTOMApper.MapToVMFromDTO(bar));

                var cocktailDTO = await this.cocktailService.GetCocktailAsync(id); ;

                if (cocktailDTO == null)
                {
                    this.toaster.AddWarningToastMessage(ToastrConsts.NotFound);
                    return RedirectToAction(nameof(Index));
                }

                var editCocktailVM = new EditCocktailViewModel
                {
                    Id = cocktailDTO.Id,
                    Name = cocktailDTO.Name,
                    ContainedBars = cocktailDTO.Bars.Select(b => b.Id).ToList(),
                    ContainedIngredients = cocktailDTO.Ingredients.Select(i => i.Id).ToList(),
                };

                ViewData["Ingredients"] = new MultiSelectList(ingredientVMs, "Id", "Name");
                ViewData["Bars"] = new MultiSelectList(barVMs, "Id", "Name");

                return View(editCocktailVM);
            }
            catch (Exception)
            {
                this.toaster.AddWarningToastMessage(ToastrConsts.GenericError);
                return RedirectToAction(nameof(Edit), new { id });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Cocktail Magician")]

CocktailMagician/CocktailMagician/Views/CocktailReviews/CocktailReviews.cshtml
@model CocktailMagician.Web.Models.ListCocktailReviewsViewModel

@{
    ViewData["Title"] = "CocktailReviews";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Reviews</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ReviewComment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.AllCocktailReviews)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Comment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    @if (User.IsInRole("Bar Crawler"))
    {
    <a asp-action="Edit" asp-route-id="@Model.CocktailId" class="btn btn-primary font-weight-bold">Edit your review</a>
        <a asp-action="Delete" asp-route-id="@Model.CocktailId" class="btn btn-primary font-weight-bold">Delete your review</a>
    }
    <a asp-action="Index" asp-controller="Cocktails" class="btn btn-primary font-weight-bold">Back to Cocktails</a>
</div>
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

CocktailMagician/CocktailMagician/Views/CocktailReviews/Create.cshtml
@model CocktailMagician.Web.Models.CreateCocktailReviewViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css" rel="stylesheet">*@
@*<link href="http://netdna.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.css" rel="stylesheet">
<link href="~/StarRating/css/star-rating.css" media="all" rel="stylesheet" type="text/css" />*@

<h1 style="color:white">Create</h1>

<h4 style="color:white">Cocktail Review</h4>
<hr />
<div class="row" style="color:white">
    <div class="col-md-6">
        <form asp-action="Create" asp-route-id="@Model.CocktailId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <textarea asp-for="Comment" class="form-control" rows="3" style="width:60%;resize:none"></textarea>
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group col-md-7">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div>
                <input type="hidden" asp-for="@Model.CocktailId" value="@Model.CocktailId" />
            </div>
            @if (User.IsInRole("Bar Crawler"))
            {
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary font-weight-bold" />
                </div>
            }
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary font-weight-bold" asp-controller="Cocktails" asp-action="Details"
       asp-route-id="@Model.CocktailId">Back to Cocktail</a>
    <a class="btn btn-primary font-weight-bold" asp-controller="Cocktails" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @*<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.js"></script>
    <script src="~/StarRating/js/star-rating.js" type="text/javascript"></script>
    <script>$("#Rating").rating({ min: 0, max: 5, step: 0.5, size: 'md' });</script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}*@
}

CocktailMagician/CocktailMagician/Views/CocktailReviews/Delete.cshtml
@model CocktailMagician.Web.Models.CocktailReviewViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this review?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
    </dl>
    @if (User.IsInRole("Bar Crawler"))
    {
        <form asp-action="Delete">
            <input type="hidden" asp-for="CocktailId" />
            <input type="hidden" asp-for="AuthorId" />
            <input type="submit" value="Delete" class="btn btn-danger font-weight-bold" />
            <a class="btn btn-primary font-weight-bold" asp-controller="Cocktails" asp-action="Index">Back to List</a>
        </form>
    }
</div>
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

CocktailMagician/CocktailMagician/Views/CocktailReviews/Details.cshtml
@model CocktailMagician.Web.Models.CocktailReviewViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>CocktailssUsersReviews</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole("Bar Crawler"))
    {
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ })
    }
    <a class="btn btn-primary font-weight-bold" asp-controller="CocktailReviews" asp-action="CocktailReviews">Back to List</a>
    <a class="btn btn-primary font-weight-bold" asp-controller="Cocktails" asp-action="Index">Back to Cocktails</a>
</div>
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

CocktailMagician/CocktailMagician/Views/CocktailReviews/Edit.cshtml
@model CocktailMagician.Web.Models.CocktailReviewViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<link href="http://netdna.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.css" rel="stylesheet">
<link href="~/StarRating/css/star-rating.css" media="all" rel="stylesheet" type="text/css" />*@

<h1 style="color:white">Edit</h1>

<hr />
<div class="row" style="color:white;">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CocktailId" />
            <input type="hidden" asp-for="AuthorId" />
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <textarea asp-for="Comment" class="form-control" rows="3" style="width:60%;resize:none"></textarea>
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group col-md-7">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            @if (User.IsInRole("Bar Crawler"))
            {
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary font-weight-bold" />
                </div>
            }
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary font-weight-bold" asp-controller="CocktailReviews" asp-action="CocktailReviews">Back to List</a>
    <a class="btn btn-primary font-weight-bold" asp-controller="Cocktails" asp-action="Index">Back to Cocktails</a>
</div>

@section Scripts {
    @*<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.js"></script>
    <script src="~/StarRating/js/star-rating.js" type="text/javascript"></script>
    <script>$("#Rating").rating({ min: 0, max: 5, step: 0.5, size: 'md' });</script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}*@
}

CocktailMagician/CocktailMagician/Views/CocktailReviews/UserReviews.cshtml
@model CocktailMagician.Web.Models.ListCocktailReviewsViewModel
@{
    ViewData["Title"] = "BarReviews";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Reviews</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ReviewComment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.AllCocktailReviews)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Comment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @if (User.IsInRole("Bar Crawler"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ })
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ });
                    }
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                </td>
            </tr>
        }
    </tbody>
</table>
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}